baseurl = "http://mschoch.github.io/poppop/"
languageCode = "en-us"
title = "Pop-Pop"
[[menu.main]]
    name = "about"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about/"
